### ISSUE TITLE
Question about 'Dp_main = sum(t_list) / sum(n_list)'

### ISSUE THREAD

**Issue by XueyunF** [pontussk/popstats#3]
Hi Pontus
I am trying to run the D-statistics. I followed your suggestion to put the population name in the first column. Then I feed popstats.py with my .tped and .tfam file then it  shows

########################################
Traceback (most recent call last):
  File "popstats.py", line 2105, in <module>
    Dp_main = sum(t_list) / sum(n_list)
ZeroDivisionError: integer division or modulo by zero
########################################

Command I used was 
python2 popstats.py -p good.tped -f good.tfam --not23 \
-b 1000000 --pops pop1,pop2,pop3,pop4 --informative 

What kind of error in my data lead to this?

Thank you!

**Comment by pontussk** [comment]
Hi!

Thanks for using popstats. You need to change how you specify the input files. Could you try

python2 popstats.py --tped good.tped --tfam good.tfam --not23 --pops pop1,pop2,pop3,pop4 --informative

?

**Comment by XueyunF** [comment]
Hi 
Thanks, I tried to modify my command lines but it still show the same error.

Below is how my tped file looks 
1	LG1:31384	0	31384	T	T	T	C	T	T	T	T	T	T	T	T	T	T	T	T	T	T	0	T	0	0	T	T	T	T	T	T	T
1	LG1:31396	0	31396	A	T	T	T	G	T	T	T	T	T	T	T	T	T	T	T	T	T	T	T	T	0	T	C	T	T	T	T	T
And tfam
pop	indv1	indv1	0	0	0	0
pop	indv2	indv2	0	0	0	0

Thanks for help!

**Comment by pontussk** [comment]
Hi,

Your tfam file should have e.g. "pop1" or "pop2" and not just "pop" in the first column. If changing this doesn't work, would it be possible for you to send your whole file to me by email?

Pontus

**Comment by XueyunF** [comment]
Hi
Thanks, in my tfam it is like
pop1	indv1	indv1	0	0	0	0
pop1	indv2	indv2	0	0	0	0
pop1	indv3	indv3	0	0	0	0
pop2	indv4	indv4	0	0	0	0
pop2	indv5	indv5	0	0	0	0
pop3	indv6	indv7	0	0	0	0
pop4	indv7	indv7	0	0	0	0

Of course I can send my tfam and tped to you. Can you give me your email address please?

Thanks for helping!

**Comment by pontussk** [comment]
skoglund@genetics.med.harvard.edu

**Comment by XueyunF** [comment]
Hi
Many thanks!
I solved the problem, it is because of the data filtering that my outgroup data was mistakenly filtered.

**Comment by pontussk** [comment]
Great, thanks for your interest in popstats!

**Comment by alx552** [comment]
Hi, 
I too an trying to runt eh D-statistic and have a similar error when running the command python2 popstats.py --tped stacks10_r0.6_7pops.tped --tfam stacks10_r0.6_7pops.tfam --not23 --pops boutoniana,pterocalyx,nodosa,borbonica --informative

ERROR
**Traceback (most recent call last):
  File "popstats.py", line 1838, in <module>
    Dp_main = sum(t_list) / sum(n_list)
ZeroDivisionError: integer division or modulo by zero**

and my .tfam file looks similar,  I was wondering what could be going wrong?  @tomatomaolajiao could my outgroup data have been mistakenly filtered as well in a similar way to yours? 
boutoniana	10_01	0	0	0	0
boutoniana	10_02	0	0	0	0
boutoniana	10_03	0	0	0	0
boutoniana	10_04	0	0	0	0
pterocalyx	84_03	0	0	0	0
pterocalyx	84_04	0	0	0	0
nodosa	87_05	0	0	0	0
nodosa	87_07	0	0	0	0
etc. 

my .tped file looks like 
0	5_3	0	149	G	G	G	G	G	G	G	G	G	A	G	A	G

**Comment by pontussk** [comment]
Hi,

Are all your chromosome names 0? Try changing them to 1 or >1. Also,
depending on your genome size you might need to change the default block
size of 5 mb in order to be able to run a proper jackknife to estimate
standard errors.

Best,
Pontus

**Comment by alx552** [comment]
I have changed the chromosome names to 1 (this is a RADseq dataset).  I am not sure how to change the default block size. None of the program options really jumped out as being able to change that.  When I run the same command as above with chromosomes all named 1, I get the following 
**genocount != popcount, 634 176**
I am not sure what this means, and no output file is produced?

**Comment by pontussk** [comment]
Hi,

This error message suggests that you don't have the same number of
individuals in your tped and tfam files. Perhaps try running them through
plink to make sure they seem correct.

Pontus

**Comment by alx552** [comment]
I think I have corrected the error to ensure the same number of individuals are in both tped and tfam files. However, when I run the program I still get an error:
**Traceback (most recent call last):
  File "popstats.py", line 2166, in <module>
    D_pop =sumt / sumn
ZeroDivisionError: float division by zero**

**Comment by pontussk** [comment]
Hi,

Can you please send me both your files or upload them somewhere?

Best,
Pontus

**Comment by pontussk** [comment]
Thanks for sending the files. Also posting my reply here with your
population labels redacted.

The problem is that your data only spans 750kb but the default block size
for the jackknife is 5 mb blocks (or separate for chromosomes). If you
truly believe that all these markers are not in LD with each other you can
set the block size to 1 (--block_size 1), so that each SNP is treated as
independent. I ran this command, see also the output.

python popstats.py --tped NNN.tped --tfam NNN.tfam --not23 --pops A,B,X,Y
--informative --block_size 1
A     B     X     Y     0.271476194992     0.0818491532067
3.31678684942     137     137     50     42     46     38

**Comment by alx552** [comment]
Thanks so much Pontus! 

So, if I am interpreting this correctly, the positive D-stat indicates admixture between A and X? 
Also given that I know the phylogeny of these species I rearranged the populations and set pop Y to be the ancestor.  I get a D-stat of -0.03, given this is close to 0. would I interpret this to mean there is admixture between pop X and Y?

**Comment by pontussk** [comment]
Yes the positive D-statistic suggests gene flow between A and X and/or
between B and Y.

To see if your D-statistic is significantly deviating from 0, look at the
Z-score in column 7, common thresholds for significance are |Z| >2 or |Z|
>3.

**Comment by emrahkirdok** [comment]
Dear Pontus,

I have also exact same problem. Could you help me on that stuff? I am sending you tped and tfam files by e-mail.

thank you.

**Comment by emrahkirdok** [comment]
I solved this problem. So please ignore my question. Thank you.
emrah

**Comment by mthang** [comment]
I encountered the same error when I tested popstats.py with my data.
genocount != popcount, 2 8

my tped and tfam file (both generated using plink)
21 . 0 9411193 G G
21 rs75025155 0 9411327 G C
21 rs78200054 0 9411410 T C
21 rs71235073 0 9411500 T G
21 rs368646645 0 9411602 C T
21 rs76676778 0 9411609 T G
21 rs71235074 0 9411645 G A
21 rs71235075 0 9411785 T G

BKP01 BKP01 0 0 0 -9
BKP02 BKP02 0 0 0 -9
BKP03 BKP03 0 0 0 -9
BKP04 BKP04 0 0 0 -9

I have no idea what's going on.

**Comment by pontussk** [comment]
Your tfam file describes four individuals but as you can see your tped file
only has two chromosomes represented.
